const PAYMENT_STATUS = {
    INITIATED: "INITIATED",
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    REVERSED: "REVERSED",
};

const PAYMENT_DIRECTION = {
    DEPOSIT: "DEPOSIT",
    WITHDRAWAL: "WITHDRAWAL",
};

const PAYMENT_PROVIDER = {
    SIMULATED: "simulated",
};

const TRANSACTION_STATUS = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    REVERSED: "REVERSED",
};

const TRANSACTION_TYPE = {
    DEPOSIT: "deposit",
    WITHDRAWAL: "withdrawal",
};

const LEDGER_ACCOUNT_TYPE = {
    AVAILABLE: "AVAILABLE",
    WITHDRAWAL_PENDING: "WITHDRAWAL_PENDING",
};

const LEDGER_ENTRY_TYPE = {
    OPENING_BALANCE: "OPENING_BALANCE",
    DEPOSIT_CREDIT: "DEPOSIT_CREDIT",
    DEPOSIT_REVERSAL: "DEPOSIT_REVERSAL",
    WITHDRAWAL_RESERVE: "WITHDRAWAL_RESERVE",
    WITHDRAWAL_RELEASE: "WITHDRAWAL_RELEASE",
    WITHDRAWAL_SETTLE: "WITHDRAWAL_SETTLE",
};

const TERMINAL_PAYMENT_STATUSES = new Set([
    PAYMENT_STATUS.COMPLETED,
    PAYMENT_STATUS.FAILED,
    PAYMENT_STATUS.CANCELLED,
    PAYMENT_STATUS.REVERSED,
]);

const PAYMENT_STATUS_TRANSITIONS = {
    [PAYMENT_STATUS.INITIATED]: new Set([
        PAYMENT_STATUS.PENDING,
        PAYMENT_STATUS.PROCESSING,
        PAYMENT_STATUS.COMPLETED,
        PAYMENT_STATUS.FAILED,
        PAYMENT_STATUS.CANCELLED,
    ]),
    [PAYMENT_STATUS.PENDING]: new Set([
        PAYMENT_STATUS.PROCESSING,
        PAYMENT_STATUS.COMPLETED,
        PAYMENT_STATUS.FAILED,
        PAYMENT_STATUS.CANCELLED,
    ]),
    [PAYMENT_STATUS.PROCESSING]: new Set([
        PAYMENT_STATUS.COMPLETED,
        PAYMENT_STATUS.FAILED,
        PAYMENT_STATUS.CANCELLED,
    ]),
    [PAYMENT_STATUS.COMPLETED]: new Set([PAYMENT_STATUS.REVERSED]),
    [PAYMENT_STATUS.FAILED]: new Set([]),
    [PAYMENT_STATUS.CANCELLED]: new Set([]),
    [PAYMENT_STATUS.REVERSED]: new Set([]),
};

module.exports = {
    PAYMENT_STATUS,
    PAYMENT_DIRECTION,
    PAYMENT_PROVIDER,
    TRANSACTION_STATUS,
    TRANSACTION_TYPE,
    LEDGER_ACCOUNT_TYPE,
    LEDGER_ENTRY_TYPE,
    TERMINAL_PAYMENT_STATUSES,
    PAYMENT_STATUS_TRANSITIONS,
};
